name: genesisos_app
description: GenesisOS Flutter app (Supabase + dotenv)
publish_to: "none"
version: 1.0.14+14

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.6
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.3.2        # <-- compatible version
  shared_preferences: ^2.2.3
  flutter_markdown: ^0.6.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
