name: genesisos_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version + build number
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # Core packages
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.0.2

  # Sprint-1 additions
  google_fonts: ^6.1.0       # custom fonts
  flutter_markdown: ^0.6.17  # markdown preview
  animations: ^2.0.8         # fade / slide helpers

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

