name: genesisos_app
description: GenesisOS Flutter app (Supabase + dotenv)
publish_to: "none"

# App version: 1.0.4 (build 4). You can bump this later.
version: 1.0.4+4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Supabase client for Flutter
  supabase_flutter: ^2.5.6

  # Load .env file bundled as an asset
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Bundle your environment file so the app can read it at runtime
  assets:
    - .env
