name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Mirrors help if network is flaky; safe to keep
      FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn
      PUB_HOSTED_URL: https://pub.flutter-io.cn
      GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8 -Dorg.gradle.internal.http.socketTimeout=120000 -Dorg.gradle.internal.http.connectionTimeout=120000"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter 3.32.8
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.32.8'
          cache: true

      # <<< NEW: auto-detect the Flutter SDK root and export FLUTTER_HOME >>>
      - name: Discover FLUTTER_HOME
        run: echo "FLUTTER_HOME=$(dirname $(dirname $(which flutter)))" >> $GITHUB_ENV
        shell: bash

      - name: Print Flutter info
        run: |
          echo "FLUTTER_HOME=$FLUTTER_HOME"
          flutter --version
          flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/**/*.apk
          if-no-files-found: error
