name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Pin the Flutter SDK location so settings.gradle.kts can include the Flutter Gradle plugin
      FLUTTER_HOME: /opt/hostedtoolcache/flutter/3.32.8-stable/x64

      # Mirrors help in regions with slow access to Google/Maven Central (safe to keep)
      FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn
      PUB_HOSTED_URL: https://pub.flutter-io.cn

      # Slightly higher timeouts for flaky networks
      GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8 -Dorg.gradle.internal.http.socketTimeout=120000 -Dorg.gradle.internal.http.connectionTimeout=120000"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter 3.32.8
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.32.8'
          cache: true

      - name: Flutter doctor
        run: |
          flutter --version
          flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/**/*.apk
          if-no-files-found: error
