name: Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.32.8"
          cache: true

      - run: flutter pub get

      # Build with Supabase values injected at compile time via repo secrets
      - name: Build release APK
        run: |
          flutter build apk --release \
            --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --dart-define=SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}

      # Read version from the APK and create a clearly named copy
      - name: Rename with version
        shell: bash
        run: |
          FILE="build/app/outputs/flutter-apk/app-release.apk"
          AAPT="$(ls -d $ANDROID_HOME/build-tools/* | sort -r | head -n1)/aapt"
          VER="$($AAPT dump badging "$FILE" | sed -n "s/.*versionName='\([^']*\)'.*/\1/p")"
          cp "$FILE" "build/app/outputs/flutter-apk/app-release-$VER.apk"
          echo "Built version: $VER"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/flutter-apk/app-release-*.apk
          if-no-files-found: error
