name: Android APK (release artifact)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  VERSION_NAME: 1.0.${{ github.run_number }}
  VERSION_CODE: ${{ github.run_number }}

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.32.8"
          cache: true

      - run: flutter pub get
      - run: flutter doctor -v || true

      - name: Build release APK (dart-define)
        run: |
          flutter build apk --release \
            --build-name="${VERSION_NAME}" \
            --build-number="${VERSION_CODE}" \
            --dart-define=SUPABASE_URL=https://pmxriyrzlkscisvgcjow.supabase.co \
            --dart-define=SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBteHJpeXJ6bGtzY2lzdmdjam93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjQ0OTcsImV4cCI6MjA2OTMwMDQ5N30.qfNPGiFJQN-wi5oKVYzMjEdFbrDcD7RRP0-_merMuFM

      - name: List outputs
        run: |
          echo "== OUTPUT TREE ==" && ls -R build/app/outputs || true
          echo "== FLUTTER-APK ==" && ls -l build/app/outputs/flutter-apk || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: genesisos-apk-${{ env.VERSION_NAME }}
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/flutter-apk/*-release.apk
          if-no-files-found: error
          retention-days: 14
