name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"
          channel: "stable"
          cache: true

      # 3. Install Java (needed for Gradle)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # 4. Set environment variables for Flutter & Android
      - name: Set environment variables
        run: |
          echo "FLUTTER_HOME=${{ env.HOME }}/flutter" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=${{ env.ANDROID_HOME }}" >> $GITHUB_ENV

      # 5. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 6. Build APK
      - name: Build release APK
        run: flutter build apk --release

      # 7. Upload APK as artifact
      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
