name: Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Build uses version from pubspec.yaml
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.32.8"
          cache: true

      - run: flutter pub get
      - run: flutter doctor -v || true

      - name: Build release APK
        run: flutter build apk --release

      - name: Show outputs
        run: ls -R build/app/outputs || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
